//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonoSoftware.MonoX.Resources {
    using System;
    using System.Web.Configuration;
    using MonoSoftware.Web.ResourceProviderModel;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorProviderModel custom tool. (Mono Wrapper based on Dmytro Kryvko builder)
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorProviderModel custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2013 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("MonoSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "4.7.40.4282")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class JavascriptMessages {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JavascriptMessages() {
        }
        
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            System.Threading.Interlocked.Exchange(ref _resourceManager, MonoSoftware.Web.ResourceProviderModel.ResourceManagerProvider.GetResourceManager("MonoSoftware.MonoX.MonoX.Resources.JavascriptMessages", typeof(JavascriptMessages).Assembly));
                        }
                    }
                    finally {
                        System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Right click here to see more options...'.
        /// </summary>
        public static string ClickHere {
            get {
                return ResourceManager.GetString("ClickHere", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Copy'.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Cut'.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Delete'.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Currently selected item will be deleted. Continue?'.
        /// </summary>
        public static string DeleteConfirmation {
            get {
                return ResourceManager.GetString("DeleteConfirmation", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'You will delete the selected message and unsubscribe from the message thread it belongs to. You will not receive any more replies to this thread, if you are not the sender of the initial message in the thread. Continue?'.
        /// </summary>
        public static string DeleteConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteConfirmationMessage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error'.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage page templates'.
        /// </summary>
        public static string ManagePageTemplates {
            get {
                return ResourceManager.GetString("ManagePageTemplates", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Manage Web parts'.
        /// </summary>
        public static string ManageWebParts {
            get {
                return ResourceManager.GetString("ManageWebParts", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New'.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New container page'.
        /// </summary>
        public static string NewContainerPage {
            get {
                return ResourceManager.GetString("NewContainerPage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New external page'.
        /// </summary>
        public static string NewExternalPage {
            get {
                return ResourceManager.GetString("NewExternalPage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New folder'.
        /// </summary>
        public static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'New page'.
        /// </summary>
        public static string NewPage {
            get {
                return ResourceManager.GetString("NewPage", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a name for a new page.'.
        /// </summary>
        public static string NewPagePrompt {
            get {
                return ResourceManager.GetString("NewPagePrompt", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Page properties'.
        /// </summary>
        public static string PageProperties {
            get {
                return ResourceManager.GetString("PageProperties", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Paste'.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Properties'.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Rename'.
        /// </summary>
        public static string Rename {
            get {
                return ResourceManager.GetString("Rename", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Please enter a new name for this item.'.
        /// </summary>
        public static string RenamePrompt {
            get {
                return ResourceManager.GetString("RenamePrompt", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Roles'.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Set URL'.
        /// </summary>
        public static string SetUrl {
            get {
                return ResourceManager.GetString("SetUrl", _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Upload'.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", _resourceCulture);
            }
        }
        
        /// <summary>
        /// The stub formatting method returning the ClickHere property value.
        /// </summary>
        /// <returns>The ClickHere property value.</returns>
        public static string ClickHereFormat() {
            return ClickHere;
        }
        
        /// <summary>
        /// The stub formatting method returning the Copy property value.
        /// </summary>
        /// <returns>The Copy property value.</returns>
        public static string CopyFormat() {
            return Copy;
        }
        
        /// <summary>
        /// The stub formatting method returning the Cut property value.
        /// </summary>
        /// <returns>The Cut property value.</returns>
        public static string CutFormat() {
            return Cut;
        }
        
        /// <summary>
        /// The stub formatting method returning the Delete property value.
        /// </summary>
        /// <returns>The Delete property value.</returns>
        public static string DeleteFormat() {
            return Delete;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteConfirmation property value.
        /// </summary>
        /// <returns>The DeleteConfirmation property value.</returns>
        public static string DeleteConfirmationFormat() {
            return DeleteConfirmation;
        }
        
        /// <summary>
        /// The stub formatting method returning the DeleteConfirmationMessage property value.
        /// </summary>
        /// <returns>The DeleteConfirmationMessage property value.</returns>
        public static string DeleteConfirmationMessageFormat() {
            return DeleteConfirmationMessage;
        }
        
        /// <summary>
        /// The stub formatting method returning the Error property value.
        /// </summary>
        /// <returns>The Error property value.</returns>
        public static string ErrorFormat() {
            return Error;
        }
        
        /// <summary>
        /// The stub formatting method returning the ManagePageTemplates property value.
        /// </summary>
        /// <returns>The ManagePageTemplates property value.</returns>
        public static string ManagePageTemplatesFormat() {
            return ManagePageTemplates;
        }
        
        /// <summary>
        /// The stub formatting method returning the ManageWebParts property value.
        /// </summary>
        /// <returns>The ManageWebParts property value.</returns>
        public static string ManageWebPartsFormat() {
            return ManageWebParts;
        }
        
        /// <summary>
        /// The stub formatting method returning the New property value.
        /// </summary>
        /// <returns>The New property value.</returns>
        public static string NewFormat() {
            return New;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewContainerPage property value.
        /// </summary>
        /// <returns>The NewContainerPage property value.</returns>
        public static string NewContainerPageFormat() {
            return NewContainerPage;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewExternalPage property value.
        /// </summary>
        /// <returns>The NewExternalPage property value.</returns>
        public static string NewExternalPageFormat() {
            return NewExternalPage;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewFolder property value.
        /// </summary>
        /// <returns>The NewFolder property value.</returns>
        public static string NewFolderFormat() {
            return NewFolder;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewPage property value.
        /// </summary>
        /// <returns>The NewPage property value.</returns>
        public static string NewPageFormat() {
            return NewPage;
        }
        
        /// <summary>
        /// The stub formatting method returning the NewPagePrompt property value.
        /// </summary>
        /// <returns>The NewPagePrompt property value.</returns>
        public static string NewPagePromptFormat() {
            return NewPagePrompt;
        }
        
        /// <summary>
        /// The stub formatting method returning the PageProperties property value.
        /// </summary>
        /// <returns>The PageProperties property value.</returns>
        public static string PagePropertiesFormat() {
            return PageProperties;
        }
        
        /// <summary>
        /// The stub formatting method returning the Paste property value.
        /// </summary>
        /// <returns>The Paste property value.</returns>
        public static string PasteFormat() {
            return Paste;
        }
        
        /// <summary>
        /// The stub formatting method returning the Properties property value.
        /// </summary>
        /// <returns>The Properties property value.</returns>
        public static string PropertiesFormat() {
            return Properties;
        }
        
        /// <summary>
        /// The stub formatting method returning the Rename property value.
        /// </summary>
        /// <returns>The Rename property value.</returns>
        public static string RenameFormat() {
            return Rename;
        }
        
        /// <summary>
        /// The stub formatting method returning the RenamePrompt property value.
        /// </summary>
        /// <returns>The RenamePrompt property value.</returns>
        public static string RenamePromptFormat() {
            return RenamePrompt;
        }
        
        /// <summary>
        /// The stub formatting method returning the Roles property value.
        /// </summary>
        /// <returns>The Roles property value.</returns>
        public static string RolesFormat() {
            return Roles;
        }
        
        /// <summary>
        /// The stub formatting method returning the SetUrl property value.
        /// </summary>
        /// <returns>The SetUrl property value.</returns>
        public static string SetUrlFormat() {
            return SetUrl;
        }
        
        /// <summary>
        /// The stub formatting method returning the Upload property value.
        /// </summary>
        /// <returns>The Upload property value.</returns>
        public static string UploadFormat() {
            return Upload;
        }
    }
}
